### ISSUE TITLE
I can't seem to run the test.py. 

### ISSUE THREAD

**Issue by Jidenna** [cjy1992/gym-carla#14]
Every time I run it I get the error below. 
**P.S.** I am also running the carla server with the command ./CarlaUE4.sh -windowed -carla-port=2000 before running the test script

```
(driving) joshua@joshua:~/gym-carla$ python test.py 
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
connecting to Carla server...
Traceback (most recent call last):
  File "test.py", line 55, in <module>
    main()
  File "test.py", line 43, in main
    env = gym.make('carla-v0', params=params)
  File "/home/joshua/anaconda/envs/driving/lib/python3.6/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/home/joshua/anaconda/envs/driving/lib/python3.6/site-packages/gym/envs/registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "/home/joshua/anaconda/envs/driving/lib/python3.6/site-packages/gym/envs/registration.py", line 73, in make
    env = cls(**_kwargs)
  File "/home/joshua/gym-carla/gym_carla/envs/carla_env.py", line 90, in __init__
    self.world = client.load_world(params['town'])
RuntimeError: rpc::rpc_error during call in function version
```

**Comment by cjy1992** [comment]
We haven't seen this problem before, what OS and carla version are you using?

**Comment by Jidenna** [comment]
I am running Linux Ubuntu with CARLA 0.8.4. Could the carla version be the reason behind the problem. Thanks for the response

**Comment by cjy1992** [comment]
Yes please use 0.9.6 as stated in the readme.

**Comment by Jidenna** [comment]
I am actually using CARLA_0.9.6 but still getting the same error message

**Comment by SHITIANYU-hue** [comment]
I have the same error too
